import Head from 'next/head';

const FONT = "'Plus Jakarta Sans', 'DM Sans', system-ui, sans-serif";
const C = { primary:'#4338CA', ink:'#18181B', inkMuted:'#71717A', border:'#E4E4E7', bg:'#F4F4F8', surface:'#FFFFFF' };

export default function PrivacyPage() {
  const sections = [
    {
      title: 'Who We Are',
      body: `BookEazy provides an online appointment booking platform for small businesses in India and globally. This policy explains how we handle personal data collected through BookEazy-powered booking pages. Under India's DPDPA 2023, we act as Data Fiduciary for business owner data and Data Processor for customer data entered by business owners.`
    },
    {
      title: 'Information We Collect',
      body: `When you book an appointment through a BookEazy-powered booking page, we collect your name and phone number. Depending on the business, you may also be asked for your email address, preferred service, date of birth, gender, address, or appointment notes. This information is submitted directly to the business you are booking with. We do not collect Aadhaar, PAN, financial account numbers, biometric data, or sensitive health information.`
    },
    {
      title: 'How Your Information Is Used',
      body: `Your details are used solely to manage your appointment. The business you book with uses your name and phone number to confirm your booking, send reminders via WhatsApp, and contact you about any changes. BookEazy facilitates this service but does not use your data for advertising, profiling, or any purpose beyond appointment management.`
    },
    {
      title: 'WhatsApp Communications',
      body: `By submitting a booking, you may receive WhatsApp messages from the business owner regarding your appointment — such as a confirmation or reminder. These messages are sent manually by the business owner from their own device using a pre-filled link generated by BookEazy. BookEazy does not send messages automatically and does not access your WhatsApp account or conversations.\n\nYou can opt out at any time by replying STOP to any WhatsApp message from the business, or by emailing privacy@bookeazy.in with your phone number. Opt-out requests are actioned within 48 hours.`
    },
    {
      title: 'Google Sign-In & Firebase',
      body: `BookEazy uses Google Firebase for authentication (business owner accounts only) and crash reporting. Customer booking data is not linked to any Google account. Firebase Crashlytics may collect anonymised technical data (device model, OS version, app version) to maintain app reliability. No personal or appointment data is included in crash reports. Google's privacy policy applies to Firebase services: policies.google.com/privacy`
    },
    {
      title: 'Data Storage & Security',
      body: `Your booking information is stored securely on Supabase — a SOC 2 Type II certified, GDPR-compliant cloud database. Data is encrypted at rest (AES-256) and in transit (TLS 1.3). Row-Level Security is enforced at the database level, meaning no business can access another business's customer data. Your data is associated only with the specific business you booked with and is never shared across businesses or with third parties.`
    },
    {
      title: 'Data Retention',
      body: `Your booking information is retained for as long as you have a booking history with a business, and for up to 12 months from your last appointment date, after which it is automatically deleted. If you wish to have your data deleted sooner, email privacy@bookeazy.in with the subject line "Delete my data" and include the phone number used during booking. We will action the request within 48 hours.`
    },
    {
      title: 'Your Rights',
      body: `Regardless of your location, you have the right to access, correct, or request deletion of your personal data at any time. You may also withdraw consent to WhatsApp communications or request a copy of your data in a readable format. To exercise any right, email privacy@bookeazy.in. We respond within 48 hours. EU and UK users may also raise a complaint with their local data protection authority.`
    },
    {
      title: 'No Data Selling',
      body: `We do not sell, rent, or trade your personal data to any third parties under any circumstances. Your data is never used for advertising or third-party profiling.`
    },
    {
      title: 'Disclaimer',
      body: `BookEazy is a scheduling and communication tool only. We are not a party to any appointment or service agreement between you and the business you book with. All service delivery, cancellations, and disputes are solely between you and the business owner. Use of any BookEazy-powered booking page is at your own discretion.`
    },
    {
      title: 'Contact & Grievance Officer',
      body: `For any privacy-related queries, data requests, or opt-out requests:\n\nEmail: teambookeazy@gmail.com\nGrievance Officer: SK Chopra \nResponse within 48 hours · Data deletion actioned within 48 hours\n\nAs required under India's IT Act 2000 and DPDPA 2023, you may also raise a grievance at grievance@bookeazy.in.`
    },
  ];

  return (
    <>
      <Head>
        <title>Privacy Policy — BookEazy</title>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet"/>
        <style>{`*, *::before, *::after{box-sizing:border-box;margin:0;padding:0} body{margin:0;background:${C.bg};font-family:${FONT};color:${C.ink}}`}</style>
      </Head>
      <div style={{ minHeight:'100vh', background:C.bg, fontFamily:FONT, display:'flex', flexDirection:'column' }}>
        {/* Header */}
        <div style={{ background:`linear-gradient(135deg,#312E81,#4338CA,#6366F1)`, padding:'40px 24px 32px', textAlign:'center' }}>
          <div style={{ maxWidth:640, margin:'0 auto' }}>
            <span style={{ display:'inline-block', background:'rgba(255,255,255,.12)', border:'1px solid rgba(255,255,255,.2)', borderRadius:20, padding:'4px 14px', fontSize:11, fontWeight:800, color:'rgba(255,255,255,.85)', letterSpacing:'0.5px', marginBottom:14, textTransform:'uppercase' }}>Legal</span>
            <h1 style={{ fontSize:32, fontWeight:800, color:'#fff', letterSpacing:'-0.6px', margin:'0 0 10px', lineHeight:1.15 }}>Privacy Policy</h1>
            <p style={{ fontSize:14, color:'rgba(255,255,255,.7)', fontWeight:500 }}>Last updated: March 2026</p>
          </div>
        </div>

        {/* Body */}
        <div style={{ flex:1, maxWidth:680, margin:'0 auto', width:'100%', padding:'32px 20px 64px' }}>
          <div style={{ background:C.surface, borderRadius:20, border:`1px solid ${C.border}`, boxShadow:'0 4px 24px rgba(67,56,202,.07)', padding:'32px 32px' }}>
            <p style={{ fontSize:14, color:C.inkMuted, lineHeight:1.7, marginBottom:28, paddingBottom:24, borderBottom:`1px solid ${C.border}` }}>
              BookEazy provides an online appointment booking platform for small businesses. This policy explains how we handle personal data collected through BookEazy-powered booking pages.
            </p>
            {sections.map((s, i) => (
              <div key={i} style={{ marginBottom: i < sections.length-1 ? 28 : 0, paddingBottom: i < sections.length-1 ? 28 : 0, borderBottom: i < sections.length-1 ? `1px solid ${C.border}` : 'none' }}>
                <h2 style={{ fontSize:15, fontWeight:800, color:C.ink, margin:'0 0 10px', letterSpacing:'-0.2px' }}>
                  <span style={{ color:C.primary, marginRight:8 }}>{String(i+1).padStart(2,'0')}.</span>{s.title}
                </h2>
                <p style={{ fontSize:13.5, color:C.inkMuted, lineHeight:1.75, margin:0 }}>{s.body}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Footer */}
        <div style={{ background:`linear-gradient(135deg,#312E81,#4338CA)`, padding:'14px 24px', display:'flex', alignItems:'center', justifyContent:'center', gap:12 }}>
          <span style={{ fontSize:13, fontWeight:700, color:'#fff' }}>BookEazy ✦</span>
          <span style={{ fontSize:11, color:'rgba(255,255,255,.4)' }}>·</span>
          <a href="/" style={{ fontSize:12, color:'rgba(255,255,255,.7)', fontWeight:600, textDecoration:'none' }}>← Back</a>
          <span style={{ fontSize:11, color:'rgba(255,255,255,.4)' }}>·</span>
          <a href="mailto:teambookeazy@gmail.com" style={{ fontSize:12, color:'rgba(255,255,255,.7)', fontWeight:600, textDecoration:'none' }}>teambookazy@gmail.com</a>
        </div>
      </div>
    </>
  );
}
